### ISSUE TITLE
assert fires in DB::ApplyIndexUpdate

### ISSUE THREAD

**Issue by joelhock** [MaskRay/ccls#197]
ccls 12b34bf8b7 and llvm 7.0.1, running on mac

i have an assert firing when re-indexing certain files (the initial index works fine).  here's an approximately minimal reproducible example:
```c++
struct Yoo {};

struct Oof : Yoo {
    Oof(const char *fmt, ...) : Yoo() {}
};

#define Bar(fmt, args...) Oof("%s" fmt, ##args)

void foo() {
    throw Bar("i am on"
              "two lines");
}
```
with `.ccls` file

```
%clang
-std=gnu++17
-x
c++
# https://github.com/MaskRay/ccls/wiki/FAQ
# https://bugs.llvm.org/show_bug.cgi?id=37695
-D__cpp_deduction_guides=0
-Wno-macro-redefined
```

stacktrace:
```
* thread 1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame 0: 0x00007fff5e91223e libsystem_kernel.dylib`__pthread_kill + 10
    frame 1: 0x00007fff5e9c8c1c libsystem_pthread.dylib`pthread_kill + 285
    frame 2: 0x00007fff5e87b1c9 libsystem_c.dylib`abort + 127
    frame 3: 0x00007fff5e843868 libsystem_c.dylib`__assert_rtn + 320
  * frame 4: 0x000000010e969f62 ccls`ccls::DB::ApplyIndexUpdate(this=0x00007ffee14a2888, lid2fid=size=2, usr=15101178088434643251, kind=Func, use=0x00007f95923351f0, delta=-1)::$_8::operator()(std::__1::unordered_map<int, int, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, int> > >&, unsigned long long, ccls::Kind, ccls::Use&, int) const at query.cc:244
    frame 5: 0x000000010e959b19 ccls`auto ccls::DB::ApplyIndexUpdate(this=0x00007ffee14a2860, usr=15101178088434643251, kind=Func, entity_usr=0x00007ffee14a5ed0, entities=size=10660, p=0x00007f9590c6f708, hint_implicit=true)::$_0::operator()<std::__1::vector<ccls::QueryFunc, std::__1::allocator<ccls::QueryFunc> >, std::__1::pair<std::__1::vector<ccls::Use, std::__1::allocator<ccls::Use> >, std::__1::vector<ccls::Use, std::__1::allocator<ccls::Use> > > >(unsigned long long, ccls::Kind, llvm::DenseMap<unsigned long long, int, ccls::DenseMapInfoForUsr, llvm::detail::DenseMapPair<unsigned long long, int> >&, std::__1::vector<ccls::QueryFunc, std::__1::allocator<ccls::QueryFunc> >&, std::__1::pair<std::__1::vector<ccls::Use, std::__1::allocator<ccls::Use> >, std::__1::vector<ccls::Use, std::__1::allocator<ccls::Use> > >&, bool) const at query.cc:278
    frame 6: 0x000000010e951935 ccls`ccls::DB::ApplyIndexUpdate(this=0x00007ffee14a5e98, u=0x00007ffee14a5a38) at query.cc:320
    frame 7: 0x000000010e89a804 ccls`ccls::pipeline::Main_OnIndexed(db=0x00007ffee14a5e98, wfiles=0x00007ffee14a6ce0, update=0x00007ffee14a5a38) at pipeline.cc:464
    frame 8: 0x000000010e89bee2 ccls`ccls::pipeline::MainLoop() at pipeline.cc:632
    frame 9: 0x000000010e773cbc ccls`main(argc=2, argv=0x00007ffee14a7ca0) at main.cc:158```

**Comment by MaskRay** [comment]
Thank you for narrowing down to the reproduce! I think I've noticed the bug but didn't know why.

The bug was in commit 77a6b8

> Date:   Thu Oct 4 23:31:59 2018 -0700
>
>    Clean and update tests after Index* refactoring

```cpp
--- a/src/message_handler.cc
+++ b/src/message_handler.cc
@@ -140,9 +140,8 @@ void EmitSemanticHighlighting(DB *db, WorkingFile *wfile, QueryFile *file) {
   // Group symbols together.
   std::unordered_map<SymbolIdx, Out_CclsPublishSemanticHighlighting::Symbol>
       grouped_symbols;
-  for (auto &sym_refcnt : file->symbol2refcnt) {
-    if (sym_refcnt.second <= 0) continue;
-    SymbolRef sym = sym_refcnt.first;
+  for (auto &[sym, refcnt] : file->symbol2refcnt) {    ////////////// should not use lvalue reference here. sym will be updated (unlike unordered_map, DenseMap does not use const for its key thus my negligence)
+    if (refcnt <= 0) continue;
```

This affects incremental update so it is serious, I've amended the releases to 0.20181010.1 0.20181024.1 0.20181111.2 0.20181225.4, respectively.

**Comment by joelhock** [comment]
thanks for the quick fix; works great.  also thanks for the .ccls notes--you'd probably faint if you saw how ugly the full version is, but i'll try your suggestions out.

**Comment by joelhock** [comment]
actually i believe `%clang` is stripped out entirely now, which means the first argument in `.ccls` is ignored in that case.  seems kind of silly to have to specify `clang` as the first thing now, but at least i know how we got to that state :)

i do still need the `-x c++` to properly parse `.h` files that i've opened directly in my editor.  perhaps the inferring works only with compilation databases?

**Comment by Abbyyan** [comment]
I've meet a similar problem using compile_commands.json. The debug info with core file as follows:
```shell
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `ccls --log-file=/tmp/ccls.log'.
Program terminated with signal 6, Aborted.
#0  0x00007f38df0dd1f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-20.el7_2.x86_64 glibc-2.17-196.tl2.3.x86_64 libgcc-4.8.5-5.tl2.x86_64 libmemcached-1.0.16-5.el7.x86_64 libstdc++-4.8.5-5.tl2.x86_64 ncurses-libs-5.9-13.20130511.el7.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00007f38df0dd1f7 in raise () from /lib64/libc.so.6
#1  0x00007f38df0dea28 in abort () from /lib64/libc.so.6
#2  0x00007f38df0d6266 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f38df0d6312 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000060a554 in ccls::DB::applyIndexUpdate(ccls::IndexUpdate*)::$_1::operator()(std::__1::unordered_map<int, int, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, int> > >&, unsigned long, ccls::Kind, ccls::DeclRef&, int) const (this=0x7ffc2c949208, lid2fid=..., usr=16818923095785284134, kind=ccls::Type, dr=..., delta=-1)
    at /home/lenajin/rpmbuild/cclsmodify/src/query.cc:302
#5  0x00000000006074fa in ccls::DB::applyIndexUpdate (this=0x7ffc2c94bd70, u=0x7ffc2c94b910) at /home/lenajin/rpmbuild/cclsmodify/src/query.cc:383
#6  0x0000000000546bce in ccls::pipeline::main_OnIndexed (db=0x7ffc2c94bd70, wfiles=0x7ffc2c94c2e8, update=0x7ffc2c94b910) at /home/lenajin/rpmbuild/cclsmodify/src/pipeline.cc:511
#7  0x0000000000549340 in ccls::pipeline::mainLoop () at /home/lenajin/rpmbuild/cclsmodify/src/pipeline.cc:698
#8  0x0000000000423e2a in main (argc=2, argv=0x7ffc2c94d958) at /home/lenajin/rpmbuild/cclsmodify/src/main.cc:164
```
