### ISSUE TITLE
ccls crashes if compile_commands.json refers to non-existent file

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#338]
### Observed behavior

In order to do some work on issue #335 I needed to rebuild ccls with debugging.  When I did that and ran it with one of my compile_commands.json, it dumped core immediately during startup.

The debugger shows:
```
(gdb) bt
#0  0x00007fd02425fe97 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fd0242618db in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fd02425139a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007fd024251412 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00000000004d6521 in llvm::StringSet<llvm::MallocAllocator>::insert (this=0x7ffd3962aff0, Key=...) at /work/src/ccls/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04/include/llvm/ADT/StringSet.h:39
#5  0x00000000004d0991 in ccls::Project::LoadDirectory (this=0x7ffd3962e380, root="/work/psmith/rel/3.4-dev/", folder=...) at src/project.cc:434
#6  0x00000000004d1167 in ccls::Project::Load (this=0x7ffd3962e380, root="/work/space/") at src/project.cc:459
#7  0x0000000000593287 in ccls::Initialize (m=0x7ffd3962dd00, param=..., reply=...) at src/messages/initialize.cc:373
#8  0x0000000000593af1 in ccls::MessageHandler::initialize (this=0x7ffd3962dd00, reader=..., reply=...) at src/messages/initialize.cc:402
#9  0x000000000046f7cc in ccls::MessageHandler::<lambda(ccls::JsonReader&, ccls::ReplyOnce&)>::operator()(ccls::JsonReader &, ccls::ReplyOnce &) const (__closure=0x2c99fd0, reader=..., reply=...) at src/message_handler.cc:153
#10 0x0000000000473f9c in std::_Function_handler<void(ccls::JsonReader&, ccls::ReplyOnce&), ccls::MessageHandler::Bind(char const*, void (ccls::MessageHandler::*)(ccls::JsonReader&, ccls::ReplyOnce&))::<lambda(ccls::JsonReader&, ccls::ReplyOnce&)> >::_M_invoke(const std::_Any_data &, ccls::JsonReader &, ccls::ReplyOnce &) (__functor=..., __args#0=..., __args#1=...) at /cc/x86_64-linux/cc/generic/x86_64-generic-linux-gnu/include/c++/8.1.0/bits/std_function.h:297
#11 0x000000000047cdd4 in std::function<void (ccls::JsonReader&, ccls::ReplyOnce&)>::operator()(ccls::JsonReader&, ccls::ReplyOnce&) const (this=0x2c99f98, __args#0=..., __args#1=...) at /cc/x86_64-linux/cc/generic/x86_64-generic-linux-gnu/include/c++/8.1.0/bits/std_function.h:687
#12 0x0000000000470396 in ccls::MessageHandler::Run (this=0x7ffd3962dd00, msg=...) at src/message_handler.cc:223
#13 0x000000000049b4dd in ccls::pipeline::MainLoop () at src/pipeline.cc:655
#14 0x000000000041c5e7 in main (argc=5, argv=0x7ffd3962eab8) at src/main.cc:158
```
Looking at frame 5:
```
(gdb) fr 5
#5  0x00000000004d0991 in ccls::Project::LoadDirectory (this=0x7ffd3962e380, root="/work/space/", folder=...) at src/project.cc:434
434           if (Seen.insert(entry.filename).second)
(gdb) p entry
$2 = {
  root = "/work/space/",
  directory = "/work/space/dir",
  filename = "",
  args = std::vector of length 42, capacity 42 = {...},
  is_inferred = false,
  compdb_size = 42,
  id = -1
}
```
So the filename is empty!  I looked through my `compile_commands.json` file for the entry in question and found this:
```
{
  "directory": "/work/space/dir",
  "command": ".../g++ ... -c /work/space/dir/removed.cpp",
  "file": "/work/space/dir/removed.cpp"
},
```
This file `/work/space/dir/removed.cpp` no longer exists in my workspace because I pulled in newer changes which deleted it, but I haven't rebuilt my `compile_commands.json` file.

It looks like somewhere ccls is discovering this file is missing and creates an entry with an empty filename, then tries to use it to insert and hits the assert.

### Expected behavior

ccls should not crash if `compile_commands.json` refers to a file which no longer exists; those entries should just be ignored.

Maybe there could be some kind of error and orderly exit if ALL the files in `compile_commands.json` didn't exist, in case someone is using the completely wrong json file, but as long as at least some of the files exist ccls should continue working and ignoring the missing files.

We've even had situations where "git pull" caused entire subdirectories' worth of content to disappear.

### System information

* ccls version (`git describe --tags`): 0.20181225.9-31-gb7d9ced0
* OS: Ubuntu 18.04
* Editor: Emacs 26.1
* Language client (and version): lsp-mode-20190320.2102

**Comment by MaskRay** [comment]
Thanks for reporting this issue! This was a regression caused by the fix of #314
Fixed at HEAD.

```cpp
 std::string RealPath(const std::string &path) {
   SmallString<256> buf;
   sys::fs::real_path(path, buf);
-  return llvm::sys::path::convert_to_slash(buf);
+  return buf.empty() ? path : llvm::sys::path::convert_to_slash(buf);
 }
```
