### ISSUE TITLE
'company-diag' crash ccls when cursor at the end of buffer

### ISSUE THREAD

**Issue by SuJinpei** [MaskRay/ccls#433]
### Observed behavior

![record](https://user-images.githubusercontent.com/14050881/60558138-b2a15800-9d7a-11e9-9310-fcbfc1b2fed3.gif)

**last lsp request:**
```
Sending request 'textDocument/completion - (42)'.

Params:
{
  "textDocument": {
    "uri": "file:///tmp/cpp/test.cpp"
  },
  "position": {
    "line": 7,
    "character": 0
  },
  "context": {
    "triggerKind": 1
  }
}
```
**gdb log:**
```
(gdb) bt
#0  0x00007fb3a0561207 in raise () from /lib64/libc.so.6
#1  0x00007fb3a0562a38 in abort () from /lib64/libc.so.6
#2  0x00007fb3a055a026 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fb3a055a0d2 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000059d5bf in ccls::(anonymous namespace)::FilterCandidates (result=..., complete_text=..., begin_pos=..., end_pos=..., buffer_line=...)
    at ../src/messages/textDocument_completion.cc:117
#5  0x000000000059ebb4 in ccls::MessageHandler::<lambda(clang::CodeCompleteConsumer*)>::operator()(clang::CodeCompleteConsumer *) const (__closure=0x2c0b430, OptConsumer=0x2c0b380)
    at ../src/messages/textDocument_completion.cc:572
#6  0x000000000059fb9f in std::_Function_handler<void(clang::CodeCompleteConsumer*), ccls::MessageHandler::textDocument_completion(ccls::CompletionParam&, ccls::ReplyOnce&)::<lambda(clang::CodeCompleteConsumer*)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/sujinpei/github/ccls/Debug/ccls, CU 0x16b8286, DIE 0x1921f56>) (__functor=...,
    __args#0=<unknown type in /home/sujinpei/github/ccls/Debug/ccls, CU 0x16b8286, DIE 0x1921f56>) at /home/sujinpei/.advlocal/include/c++/8.3.0/bits/std_function.h:297
#7  0x000000000050d749 in std::function<void (clang::CodeCompleteConsumer*)>::operator()(clang::CodeCompleteConsumer*) const (this=0x2c0b160, __args#0=0x2c0b380)
    at /home/sujinpei/.advlocal/include/c++/8.3.0/bits/std_function.h:687
#8  0x00000000005073ac in ccls::(anonymous namespace)::CompletionMain (manager_=0x7fffedd756e0) at ../src/sema_manager.cc:508
#9  0x00007fb3a08ffdd5 in start_thread () from /lib64/libpthread.so.0
#10 0x00007fb3a0628ead in clone () from /lib64/libc.so.6
(gdb) frame 4
#4  0x000000000059d5bf in ccls::(anonymous namespace)::FilterCandidates (result=..., complete_text=..., begin_pos=..., end_pos=..., buffer_line=...)
    at ../src/messages/textDocument_completion.cc:117
117       assert(begin_pos.line == end_pos.line);
(gdb) print begin_pos.line
$1 = 6
(gdb) print end_pos.line
$2 = 7
```

### Expected behavior

the ccls should not crash even there is nothing to complete.

### Steps to reproduce

1. open 'test.cpp' in the Spacemacs.
2. write code as below:
```
#include <iostream>

int main(int argc, char *argv[])
{
  std::cout << "hello\n";
  return 0;
}
```
3. run 'company-diag'

### System information

* ccls version (`git describe --tags --long`): 
```
$ git describe --tags --long
fatal: No tags can describe '990925d806989f1dbd3f703ac02f8c442492c42c'.
Try --always, or create some tags.
```
* clang version: 
```
$ clang --version
clang version 9.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/sujinpei/.advlocal/bin
```
* OS:  CentOS Linux release 7.2.1511 (Core)
* Editor:  Spacemacs
* Language client (and version):

**Comment by MaskRay** [comment]
I cannot reproduce with clang trunk.

> #4  0x000000000059d5bf in ccls::(anonymous namespace)::FilterCandidates (result=..., complete_text=..., begin_pos=..., end_pos=..., buffer_line=...)
    at ../src/messages/textDocument_completion.cc:117
117       assert(begin_pos.line == end_pos.line);

Can you print more information or try building clang by yourself? The 9.0 snapshot you fetched somewhere may have completion bugs.

**Comment by SuJinpei** [comment]
try below master branch of llvm, but no luck.
```
llvm-project]$ git describe
git describe
fatal: No tags can describe '2b20ee4110ec69402ec84ea3a122df8c7eacc144'.
Try --always, or create some tags.

```

I want to find out where the bug is. Could you give some debug guidance?😊

**Comment by MaskRay** [comment]
Sorry for not being early to get back to this issue. But it may be obsoleted now? https://github.com/MaskRay/ccls/wiki/Debugging has some information for debugging.
