### ISSUE TITLE
Segmentation fault on Fedora 32

### ISSUE THREAD

**Issue by php1ic** [MaskRay/ccls#631]
### Observed behavior

Running the version of ccls available in the repository for fedora 32 causes a segmentation fault

* Not sure if this is fedora OS related so also made a ticket [here](https://ask.fedoraproject.org/t/fedora-32-ccls-program-is-looking-for-old-version-of-llvm/6828)
* Looks to be the same issue as #550 

### Expected behavior

The program to run without crashing

### Steps to reproduce

1. Install ccls from the fedora repository and clone ccls from github to have a common project to report on
2. From the fresh clone of ccls, configure a build 
```
$ cmake -H. -Brelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
$ ln -s release/compile_commands.json 
```
3. Run the fedora provided version of ccls as per [debug](https://github.com/MaskRay/ccls/wiki/Debugging) instructions.

### System information

* ccls version (`git describe --tags --long`): 0.20190823.5
* clang version: 10
* OS: Fedora 32
* Editor: n/a
* Language client (and version): n/a

### GDB Output 
```
$ gdb --args /usr/bin/ccls --index=/home/ijc/git_repos/ccls/
GNU gdb (GDB) Fedora 9.1-3.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/ccls...
Reading symbols from .gnu_debugdata for /usr/bin/ccls...
(No debugging symbols found in .gnu_debugdata for /usr/bin/ccls)
Missing separate debuginfos, use: dnf debuginfo-install ccls-0.20190823.5-3.fc32.x86_64
(gdb) run
Starting program: /usr/bin/ccls --index=/home/ijc/git_repos/ccls/
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[New Thread 0x7ffff0760700 (LWP 72261)]
[New Thread 0x7fffeff5f700 (LWP 72262)]
[New Thread 0x7fffef75e700 (LWP 72263)]
12:27:07 ccls           initialize.cc:262 I initialize in directory /home/ijc/git_repos/ccls with uri file:///home/ijc/git_repos/ccls/
12:27:07 ccls           initialize.cc:285 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":".ccls-cache","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":[],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":false,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
12:27:07 ccls           initialize.cc:314 I use -resource-dir=/usr/lib64/clang/9.0.1
12:27:07 ccls           initialize.cc:347 I workspace folder: /home/ijc/git_repos/ccls/
12:27:07 ccls              project.cc:422 I loaded /home/ijc/git_repos/ccls/compile_commands.json
12:27:07 ccls           initialize.cc:372 I start 8 indexers
[New Thread 0x7fffeef5d700 (LWP 72264)]
[New Thread 0x7fffe7fff700 (LWP 72265)]
[New Thread 0x7fffee75c700 (LWP 72266)]
[New Thread 0x7fffedf5b700 (LWP 72267)]
[New Thread 0x7fffed75a700 (LWP 72268)]
[New Thread 0x7fffecf59700 (LWP 72269)]
[New Thread 0x7fffe77fe700 (LWP 72270)]
[New Thread 0x7fffe6ffd700 (LWP 72271)]
12:27:07 ccls           initialize.cc:380 I dispatch initial index requests
entries:    42
pending:    4312:27:07 indexer4         pipeline.cc:340 I parse /home/ijc/git_repos/ccls/src/clang_tu.cc
12:27:07 indexer3         pipeline.cc:340 I parse /home/ijc/git_repos/ccls/src/config.cc
12:27:07 indexer6         pipeline.cc:340 I parse /home/ijc/git_repos/ccls/src/main.cc
12:27:07 indexer0         pipeline.cc:340 I parse /home/ijc/git_repos/ccls/src/include_complete.cc
12:27:07 indexer5         pipeline.cc:340 I parse /home/ijc/git_repos/ccls/src/indexer.cc
12:27:07 indexer7         pipeline.cc:290 I load cache for /home/ijc/git_repos/ccls/third_party/siphash.cc
12:27:07 indexer2         pipeline.cc:340 I parse /home/ijc/git_repos/ccls/src/filesystem.cc
12:27:07 indexer1         pipeline.cc:340 I parse /home/ijc/git_repos/ccls/src/fuzzy_match.cc
12:27:07 indexer7         pipeline.cc:290 I load cache for /home/ijc/git_repos/ccls/src/log.cc
12:27:07 indexer7         pipeline.cc:340 I parse /home/ijc/git_repos/ccls/src/lsp.cc
pending:    41
Thread 11 "indexer6" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe77fe700 (LWP 72270)]
0x00007ffff6172070 in clang::NestedNameSpecifier::getKind() const () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
(gdb) bt
#0  0x00007ffff6172070 in clang::NestedNameSpecifier::getKind() const () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#1  0x00007ffff63e8f4d in clang::Sema::ShouldEnterDeclaratorScope(clang::Scope*, clang::CXXScopeSpec const&) () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#2  0x00007ffff5e9448c in clang::Parser::ParseDirectDeclarator(clang::Declarator&) () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#3  0x00007ffff5e9012b in clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) ()
   from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#4  0x00007ffff5f1d119 in clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier)
    () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#5  0x00007ffff5f23d3f in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
   from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#6  0x00007ffff5ea19ba in clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#7  0x00007ffff5ea27f2 in clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) ()
   from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#8  0x00007ffff5e917a3 in clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) ()
   from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#9  0x00007ffff5f23ca1 in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
   from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#10 0x00007ffff5ea19ba in clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#11 0x00007ffff5ea27f2 in clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) ()
   from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#12 0x00007ffff5e917a3 in clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&) ()
   from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#13 0x00007ffff5f23ca1 in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
   from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#14 0x00007ffff5f255c5 in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#15 0x00007ffff5e6e829 in clang::ParseAST(clang::Sema&, bool, bool) () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#16 0x00007ffff7266269 in clang::FrontendAction::Execute() () from /usr/lib64/llvm9.0/lib/libclang-cpp.so.9
#17 0x0000555555588721 in void llvm::function_ref<void ()>::callback_fn<ccls::idx::index(ccls::SemaManager*, ccls::WorkingFiles*, ccls::VFS*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<char const*, std::allocator<char const*> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, bool, bool&)::{lambda()#1}>(long) ()
#18 0x00007ffff17a8927 in llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) () from /usr/lib64/llvm9.0/lib/libLLVM-9.so
#19 0x0000555555592222 in ccls::idx::index(ccls::SemaManager*, ccls::WorkingFiles*, ccls::VFS*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<char const*, std::allocator<char const*> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, bool, bool&) ()
#20 0x00005555555b4c45 in ccls::pipeline::(anonymous namespace)::indexer_Parse(ccls::SemaManager*, ccls::WorkingFiles*, ccls::Project*, ccls::VFS*, ccls::GroupMatch const&) ()
#21 0x00005555555b7d2c in ccls::pipeline::indexer_Main(ccls::SemaManager*, ccls::VFS*, ccls::Project*, ccls::WorkingFiles*) ()
#22 0x000055555564e22d in ccls::(anonymous namespace)::indexer(void*) ()
#23 0x00007ffff0b1d432 in start_thread () from /usr/lib64/libpthread.so.0
#24 0x00007ffff0a4b9d3 in clone () from /usr/lib64/libc.so.6
```

**Comment by php1ic** [comment]
This looks to be a bug with how ccls has been packaged in Fedora32 - [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1832258)

**Comment by XVilka** [comment]
Was fixed by the Fedora 32 update today.

**Comment by php1ic** [comment]
Can confirm. I have updated and it now works as expected.
