### ISSUE TITLE
compilation database update is not taken into consideration

### ISSUE THREAD

**Issue by free-easy** [MaskRay/ccls#96]
Hi @MaskRay ,

I'm facing this problem:
When the compilation database is updated, I need to reload vscode in order to have the update applied.

**Comment by free-easy** [comment]
I'm doing embedded development, so I have many types of build (for production hardware, development board, native tests on the development platform, hardware tests on the target hardware, etc.) and each one involves different macros to be defined (or undefined) and even different libraries to be used.

Currently I'm use CMake as build system and there is a nice extension for vscode that allows me to quickly switch between build type.
![screenshot from 2018-10-17 11-39-19](https://user-images.githubusercontent.com/20483759/47077578-89976200-d201-11e8-93aa-67726a208197.png)

The problem is that when I switch build type and the compile_commands.json is updated, `ccls` doesn't update it's semantic highlight, diagnostic, etc.

I've checked and currenly `vscode-ccls` doesn't seem to support `workspace/didChangeConfiguration`.
I've tried to use the command `ccls: Restart language server` with no success. After the language server is restarted, I have this error message in the developer console whenever I open a file.
```
TypeError: Cannot read property 'document' of undefined
	at vscode_1.window.onDidChangeActiveTextEditor.editor (/home/chenlijun/.vscode/extensions/ccls-project.ccls-0.1.16/out/extension.js:483:32)
	at e.fire (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:496)
	at /snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:588:237
	at e.fire (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:496)
	at e.$acceptDocumentsAndEditorsDelta (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:488:823)
	at t._doInvokeHandler (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:640:888)
	at t._invokeHandler (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:640:554)
	at t._receiveRequest (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:639:126)
	at t._receiveOneMessage (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:638:59)
	at /snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:635:926
	at /snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:138
	at e.fire (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:496)
	at a (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:154:213)
	at Socket._socketDataListener (/snap/vscode/63/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by MaskRay** [comment]
If you switch to different builds frequently, you may want to set `cacheFormat: ""` to not store indexes on the disk. There is very little I can do for the vscode plugin as I don't use that editor. The best way to make sure this happens is to get involved. `workspace/didChangeConfiguration` should work on the server side.

When I introduced the initialization option `index.multiVersion: int`, I typed it as `int` because I thought duplicate `"file"` entries in `compile_commands.json` should be supported some day in the future. glibc compiles many files twice, for example. If that is done, you can get a combined view of `Debug` and `Release` and don't need to switch your build configurations.

**Comment by free-easy** [comment]
Thank you for the response.
As I supposed, it's mainly a issue regarding the editor's language server client.

Feel free to close the issue and thank you again!
